policies:
  - name: CodeArtsRepo-Project-Set-Project-Inherit-Settings
    description: set project inherit settings for project
    resource: huaweicloud.codeartsrepo-project
    mode:
      type: huaweicloud-periodic
      xrole: Custodian
      enable_lts_log: true
      log_level: INFO
      schedule: "00 00 00 * * *"
      schedule_type: Cron
      cron_tz: "America/Sao_Paulo"
    actions:
      - type: set-project-inherit-settings
        protected_branches_enable: True
        watermark_enable: True
